// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdCreative = `-- name: CreateAdCreative :one
INSERT INTO ad_creatives (
  tenant_id, zone_id, title, image_url, target_url, starts_at, ends_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, zone_id, title, image_url, target_url, starts_at, ends_at, impressions, clicks, status, created_at
`

type CreateAdCreativeParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ZoneID    pgtype.UUID        `json:"zone_id"`
	Title     pgtype.Text        `json:"title"`
	ImageUrl  string             `json:"image_url"`
	TargetUrl string             `json:"target_url"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateAdCreative(ctx context.Context, arg CreateAdCreativeParams) (AdCreative, error) {
	row := q.db.QueryRow(ctx, createAdCreative,
		arg.TenantID,
		arg.ZoneID,
		arg.Title,
		arg.ImageUrl,
		arg.TargetUrl,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i AdCreative
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ZoneID,
		&i.Title,
		&i.ImageUrl,
		&i.TargetUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Impressions,
		&i.Clicks,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAdZone = `-- name: CreateAdZone :one
INSERT INTO ad_zones (
  tenant_id, code, name, placement, size, pricing_cents
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, code, name, placement, size, pricing_cents, created_at
`

type CreateAdZoneParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	Placement    string      `json:"placement"`
	Size         pgtype.Text `json:"size"`
	PricingCents pgtype.Int4 `json:"pricing_cents"`
}

func (q *Queries) CreateAdZone(ctx context.Context, arg CreateAdZoneParams) (AdZone, error) {
	row := q.db.QueryRow(ctx, createAdZone,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Placement,
		arg.Size,
		arg.PricingCents,
	)
	var i AdZone
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Placement,
		&i.Size,
		&i.PricingCents,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAdsForZone = `-- name: ListActiveAdsForZone :many
SELECT id, tenant_id, zone_id, title, image_url, target_url, starts_at, ends_at, impressions, clicks, status, created_at FROM ad_creatives
WHERE zone_id = $1 AND status = 'active'
  AND (starts_at IS NULL OR starts_at <= NOW())
  AND (ends_at IS NULL OR ends_at >= NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAdsForZone(ctx context.Context, zoneID pgtype.UUID) ([]AdCreative, error) {
	rows, err := q.db.Query(ctx, listActiveAdsForZone, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdCreative
	for rows.Next() {
		var i AdCreative
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ZoneID,
			&i.Title,
			&i.ImageUrl,
			&i.TargetUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Impressions,
			&i.Clicks,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdZones = `-- name: ListAdZones :many
SELECT id, tenant_id, code, name, placement, size, pricing_cents, created_at FROM ad_zones
WHERE tenant_id = $1
`

func (q *Queries) ListAdZones(ctx context.Context, tenantID pgtype.UUID) ([]AdZone, error) {
	rows, err := q.db.Query(ctx, listAdZones, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdZone
	for rows.Next() {
		var i AdZone
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Placement,
			&i.Size,
			&i.PricingCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
