// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_ops.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOpsFinding = `-- name: CreateOpsFinding :one
INSERT INTO ops_findings (tenant_id, type, entity, entity_id, severity, details_json)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, type, entity, entity_id, severity, details_json, status, created_at, resolved_at
`

type CreateOpsFindingParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Type        string      `json:"type"`
	Entity      string      `json:"entity"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Severity    string      `json:"severity"`
	DetailsJson []byte      `json:"details_json"`
}

func (q *Queries) CreateOpsFinding(ctx context.Context, arg CreateOpsFindingParams) (OpsFinding, error) {
	row := q.db.QueryRow(ctx, createOpsFinding,
		arg.TenantID,
		arg.Type,
		arg.Entity,
		arg.EntityID,
		arg.Severity,
		arg.DetailsJson,
	)
	var i OpsFinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Entity,
		&i.EntityID,
		&i.Severity,
		&i.DetailsJson,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createTrendSignal = `-- name: CreateTrendSignal :one
INSERT INTO trend_signals (tenant_id, category_id, score, evidence_json)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, category_id, score, evidence_json, created_at
`

type CreateTrendSignalParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Score        float64     `json:"score"`
	EvidenceJson []byte      `json:"evidence_json"`
}

func (q *Queries) CreateTrendSignal(ctx context.Context, arg CreateTrendSignalParams) (TrendSignal, error) {
	row := q.db.QueryRow(ctx, createTrendSignal,
		arg.TenantID,
		arg.CategoryID,
		arg.Score,
		arg.EvidenceJson,
	)
	var i TrendSignal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Score,
		&i.EvidenceJson,
		&i.CreatedAt,
	)
	return i, err
}

const listOpsFindings = `-- name: ListOpsFindings :many
SELECT id, tenant_id, type, entity, entity_id, severity, details_json, status, created_at, resolved_at FROM ops_findings
WHERE tenant_id = $1 AND status = 'open'
ORDER BY created_at DESC
`

func (q *Queries) ListOpsFindings(ctx context.Context, tenantID pgtype.UUID) ([]OpsFinding, error) {
	rows, err := q.db.Query(ctx, listOpsFindings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpsFinding
	for rows.Next() {
		var i OpsFinding
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Entity,
			&i.EntityID,
			&i.Severity,
			&i.DetailsJson,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopTrends = `-- name: ListTopTrends :many
SELECT id, tenant_id, category_id, score, evidence_json, created_at FROM trend_signals
WHERE tenant_id = $1
ORDER BY score DESC
LIMIT 10
`

func (q *Queries) ListTopTrends(ctx context.Context, tenantID pgtype.UUID) ([]TrendSignal, error) {
	rows, err := q.db.Query(ctx, listTopTrends, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendSignal
	for rows.Next() {
		var i TrendSignal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Score,
			&i.EvidenceJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOpsFinding = `-- name: ResolveOpsFinding :exec
UPDATE ops_findings
SET status = 'resolved', resolved_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type ResolveOpsFindingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ResolveOpsFinding(ctx context.Context, arg ResolveOpsFindingParams) error {
	_, err := q.db.Exec(ctx, resolveOpsFinding, arg.ID, arg.TenantID)
	return err
}
