// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO enterprise_audit_logs (tenant_id, actor_id, action, resource, details_json, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, actor_id, action, resource, details_json, created_at, ip, user_agent
`

type CreateAuditLogParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	Action      string      `json:"action"`
	Resource    string      `json:"resource"`
	DetailsJson []byte      `json:"details_json"`
	Ip          *netip.Addr `json:"ip"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (EnterpriseAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.DetailsJson,
		arg.Ip,
		arg.UserAgent,
	)
	var i EnterpriseAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.DetailsJson,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, actor_id, action, resource, details_json, created_at, ip, user_agent FROM enterprise_audit_logs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListAuditLogs(ctx context.Context, tenantID pgtype.UUID) ([]EnterpriseAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnterpriseAuditLog
	for rows.Next() {
		var i EnterpriseAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAuditLogs = `-- name: ListGlobalAuditLogs :many
SELECT id, tenant_id, actor_id, action, resource, details_json, created_at, ip, user_agent FROM enterprise_audit_logs
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListGlobalAuditLogs(ctx context.Context) ([]EnterpriseAuditLog, error) {
	rows, err := q.db.Query(ctx, listGlobalAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnterpriseAuditLog
	for rows.Next() {
		var i EnterpriseAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.DetailsJson,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
