// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveBlogPost = `-- name: ArchiveBlogPost :one
UPDATE posts SET 
    status = 'ARCHIVED', 
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url
`

type ArchiveBlogPostParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveBlogPost(ctx context.Context, arg ArchiveBlogPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, archiveBlogPost, arg.TenantID, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}

const createBlogPost = `-- name: CreateBlogPost :one
INSERT INTO posts (
    tenant_id, title, slug, content_json, excerpt, status, author_id, 
    sector, tags, meta_description, custom_meta_tags, og_image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 
    $8, $9, $10, $11, $12
) RETURNING id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url
`

type CreateBlogPostParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	ContentJson     []byte      `json:"content_json"`
	Excerpt         pgtype.Text `json:"excerpt"`
	Status          pgtype.Text `json:"status"`
	AuthorID        pgtype.UUID `json:"author_id"`
	Sector          pgtype.Text `json:"sector"`
	Tags            []string    `json:"tags"`
	MetaDescription pgtype.Text `json:"meta_description"`
	CustomMetaTags  pgtype.Text `json:"custom_meta_tags"`
	OgImageUrl      pgtype.Text `json:"og_image_url"`
}

func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createBlogPost,
		arg.TenantID,
		arg.Title,
		arg.Slug,
		arg.ContentJson,
		arg.Excerpt,
		arg.Status,
		arg.AuthorID,
		arg.Sector,
		arg.Tags,
		arg.MetaDescription,
		arg.CustomMetaTags,
		arg.OgImageUrl,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}

const getBlogPost = `-- name: GetBlogPost :one
SELECT id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url FROM posts 
WHERE tenant_id = $1 AND id = $2
`

type GetBlogPostParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetBlogPost(ctx context.Context, arg GetBlogPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, getBlogPost, arg.TenantID, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}

const getBlogPostBySlug = `-- name: GetBlogPostBySlug :one
SELECT id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url FROM posts 
WHERE tenant_id = $1 AND slug = $2
`

type GetBlogPostBySlugParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Slug     string      `json:"slug"`
}

func (q *Queries) GetBlogPostBySlug(ctx context.Context, arg GetBlogPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getBlogPostBySlug, arg.TenantID, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}

const getPublicPostBySlug = `-- name: GetPublicPostBySlug :one
SELECT id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url FROM posts 
WHERE tenant_id = $1 AND slug = $2 AND status = 'PUBLISHED'
`

type GetPublicPostBySlugParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Slug     string      `json:"slug"`
}

func (q *Queries) GetPublicPostBySlug(ctx context.Context, arg GetPublicPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPublicPostBySlug, arg.TenantID, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}

const getPublicPosts = `-- name: GetPublicPosts :many
SELECT id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url FROM posts 
WHERE tenant_id = $1 AND status = 'PUBLISHED' 
ORDER BY published_at DESC
`

func (q *Queries) GetPublicPosts(ctx context.Context, tenantID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPublicPosts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.ContentJson,
			&i.Excerpt,
			&i.Status,
			&i.PublishedAt,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Sector,
			&i.Tags,
			&i.MetaDescription,
			&i.CustomMetaTags,
			&i.OgImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url FROM posts 
WHERE tenant_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListBlogPosts(ctx context.Context, tenantID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listBlogPosts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.ContentJson,
			&i.Excerpt,
			&i.Status,
			&i.PublishedAt,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Sector,
			&i.Tags,
			&i.MetaDescription,
			&i.CustomMetaTags,
			&i.OgImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishBlogPost = `-- name: PublishBlogPost :one
UPDATE posts SET 
    status = 'PUBLISHED', 
    published_at = NOW(),
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url
`

type PublishBlogPostParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) PublishBlogPost(ctx context.Context, arg PublishBlogPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, publishBlogPost, arg.TenantID, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}

const updateBlogPost = `-- name: UpdateBlogPost :one
UPDATE posts SET 
    title = $3, 
    slug = $4, 
    content_json = $5, 
    excerpt = $6, 
    status = $7, 
    author_id = $8,
    sector = $9, 
    tags = $10, 
    meta_description = $11, 
    custom_meta_tags = $12, 
    og_image_url = $13,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, title, slug, content_json, excerpt, status, published_at, author_id, created_at, updated_at, sector, tags, meta_description, custom_meta_tags, og_image_url
`

type UpdateBlogPostParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	ContentJson     []byte      `json:"content_json"`
	Excerpt         pgtype.Text `json:"excerpt"`
	Status          pgtype.Text `json:"status"`
	AuthorID        pgtype.UUID `json:"author_id"`
	Sector          pgtype.Text `json:"sector"`
	Tags            []string    `json:"tags"`
	MetaDescription pgtype.Text `json:"meta_description"`
	CustomMetaTags  pgtype.Text `json:"custom_meta_tags"`
	OgImageUrl      pgtype.Text `json:"og_image_url"`
}

func (q *Queries) UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updateBlogPost,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.ContentJson,
		arg.Excerpt,
		arg.Status,
		arg.AuthorID,
		arg.Sector,
		arg.Tags,
		arg.MetaDescription,
		arg.CustomMetaTags,
		arg.OgImageUrl,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.Excerpt,
		&i.Status,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sector,
		&i.Tags,
		&i.MetaDescription,
		&i.CustomMetaTags,
		&i.OgImageUrl,
	)
	return i, err
}
