// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRBACPermission = `-- name: AddRBACPermission :one
INSERT INTO rbac_permissions (role_id, resource, action)
VALUES ($1, $2, $3)
RETURNING id, role_id, resource, action, created_at
`

type AddRBACPermissionParams struct {
	RoleID   pgtype.UUID `json:"role_id"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
}

func (q *Queries) AddRBACPermission(ctx context.Context, arg AddRBACPermissionParams) (RbacPermission, error) {
	row := q.db.QueryRow(ctx, addRBACPermission, arg.RoleID, arg.Resource, arg.Action)
	var i RbacPermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const createComplianceIssue = `-- name: CreateComplianceIssue :one
INSERT INTO compliance_issues (tenant_id, scan_id, category, severity, description, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, scan_id, category, severity, description, status, detected_at, resolved_at
`

type CreateComplianceIssueParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ScanID      pgtype.UUID `json:"scan_id"`
	Category    string      `json:"category"`
	Severity    string      `json:"severity"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateComplianceIssue(ctx context.Context, arg CreateComplianceIssueParams) (ComplianceIssue, error) {
	row := q.db.QueryRow(ctx, createComplianceIssue,
		arg.TenantID,
		arg.ScanID,
		arg.Category,
		arg.Severity,
		arg.Description,
		arg.Status,
	)
	var i ComplianceIssue
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScanID,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Status,
		&i.DetectedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createComplianceScan = `-- name: CreateComplianceScan :one
INSERT INTO compliance_scans (tenant_id, status, summary_json)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, status, summary_json, created_at, completed_at
`

type CreateComplianceScanParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Status      string      `json:"status"`
	SummaryJson []byte      `json:"summary_json"`
}

func (q *Queries) CreateComplianceScan(ctx context.Context, arg CreateComplianceScanParams) (ComplianceScan, error) {
	row := q.db.QueryRow(ctx, createComplianceScan, arg.TenantID, arg.Status, arg.SummaryJson)
	var i ComplianceScan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createEvidenceExport = `-- name: CreateEvidenceExport :one
INSERT INTO evidence_exports (tenant_id, template, format, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, template, format, status, download_url, created_by, created_at
`

type CreateEvidenceExportParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Template  string      `json:"template"`
	Format    string      `json:"format"`
	Status    string      `json:"status"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateEvidenceExport(ctx context.Context, arg CreateEvidenceExportParams) (EvidenceExport, error) {
	row := q.db.QueryRow(ctx, createEvidenceExport,
		arg.TenantID,
		arg.Template,
		arg.Format,
		arg.Status,
		arg.CreatedBy,
	)
	var i EvidenceExport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Template,
		&i.Format,
		&i.Status,
		&i.DownloadUrl,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRBACRole = `-- name: CreateRBACRole :one
INSERT INTO rbac_roles (name, description, is_system)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_system, created_at
`

type CreateRBACRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) CreateRBACRole(ctx context.Context, arg CreateRBACRoleParams) (RbacRole, error) {
	row := q.db.QueryRow(ctx, createRBACRole, arg.Name, arg.Description, arg.IsSystem)
	var i RbacRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listAllComplianceIssues = `-- name: ListAllComplianceIssues :many
SELECT id, tenant_id, scan_id, category, severity, description, status, detected_at, resolved_at FROM compliance_issues
ORDER BY detected_at DESC
LIMIT 100
`

func (q *Queries) ListAllComplianceIssues(ctx context.Context) ([]ComplianceIssue, error) {
	rows, err := q.db.Query(ctx, listAllComplianceIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceIssue
	for rows.Next() {
		var i ComplianceIssue
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScanID,
			&i.Category,
			&i.Severity,
			&i.Description,
			&i.Status,
			&i.DetectedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplianceIssues = `-- name: ListComplianceIssues :many
SELECT id, tenant_id, scan_id, category, severity, description, status, detected_at, resolved_at FROM compliance_issues
WHERE tenant_id = $1
ORDER BY detected_at DESC
`

func (q *Queries) ListComplianceIssues(ctx context.Context, tenantID pgtype.UUID) ([]ComplianceIssue, error) {
	rows, err := q.db.Query(ctx, listComplianceIssues, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceIssue
	for rows.Next() {
		var i ComplianceIssue
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScanID,
			&i.Category,
			&i.Severity,
			&i.Description,
			&i.Status,
			&i.DetectedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplianceScans = `-- name: ListComplianceScans :many
SELECT id, tenant_id, status, summary_json, created_at, completed_at FROM compliance_scans
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListComplianceScans(ctx context.Context) ([]ComplianceScan, error) {
	rows, err := q.db.Query(ctx, listComplianceScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceScan
	for rows.Next() {
		var i ComplianceScan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.SummaryJson,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceExports = `-- name: ListEvidenceExports :many
SELECT id, tenant_id, template, format, status, download_url, created_by, created_at FROM evidence_exports
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListEvidenceExports(ctx context.Context) ([]EvidenceExport, error) {
	rows, err := q.db.Query(ctx, listEvidenceExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceExport
	for rows.Next() {
		var i EvidenceExport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Template,
			&i.Format,
			&i.Status,
			&i.DownloadUrl,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRBACPermissions = `-- name: ListRBACPermissions :many
SELECT id, role_id, resource, action, created_at FROM rbac_permissions
WHERE role_id = $1
`

func (q *Queries) ListRBACPermissions(ctx context.Context, roleID pgtype.UUID) ([]RbacPermission, error) {
	rows, err := q.db.Query(ctx, listRBACPermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RbacPermission
	for rows.Next() {
		var i RbacPermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Resource,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRBACRoles = `-- name: ListRBACRoles :many
SELECT id, name, description, is_system, created_at FROM rbac_roles
ORDER BY name
`

func (q *Queries) ListRBACRoles(ctx context.Context) ([]RbacRole, error) {
	rows, err := q.db.Query(ctx, listRBACRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RbacRole
	for rows.Next() {
		var i RbacRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
