// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ecosystem.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (tenant_id, name, hash, scopes_json)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, hash, scopes_json, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Name       string      `json:"name"`
	Hash       string      `json:"hash"`
	ScopesJson []byte      `json:"scopes_json"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.Hash,
		arg.ScopesJson,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Hash,
		&i.ScopesJson,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (tenant_id, endpoint_id, event, payload_json, status, attempts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, endpoint_id, event, payload_json, status, attempts, last_attempt_at, created_at
`

type CreateWebhookDeliveryParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EndpointID  pgtype.UUID `json:"endpoint_id"`
	Event       string      `json:"event"`
	PayloadJson []byte      `json:"payload_json"`
	Status      string      `json:"status"`
	Attempts    int32       `json:"attempts"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.TenantID,
		arg.EndpointID,
		arg.Event,
		arg.PayloadJson,
		arg.Status,
		arg.Attempts,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.Event,
		&i.PayloadJson,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (tenant_id, url, secret, events_json)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, url, secret, events_json, is_active, created_at
`

type CreateWebhookEndpointParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Url        string      `json:"url"`
	Secret     string      `json:"secret"`
	EventsJson []byte      `json:"events_json"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.EventsJson,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.EventsJson,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, tenant_id, name, hash, scopes_json, last_used_at, created_at, revoked_at FROM api_keys
WHERE tenant_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Hash,
			&i.ScopesJson,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, tenant_id, url, secret, events_json, is_active, created_at FROM webhook_endpoints
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, tenantID pgtype.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.EventsJson,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type RevokeAPIKeyParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.TenantID)
	return err
}
