// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListing = `-- name: CreateListing :one
INSERT INTO listings (
  tenant_id, title, slug, category_id, status
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, tenant_id, title, slug, summary, description_md, website, category_id, status, created_at, updated_at
`

type CreateListingParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Title      string      `json:"title"`
	Slug       string      `json:"slug"`
	CategoryID pgtype.UUID `json:"category_id"`
	Status     pgtype.Text `json:"status"`
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.TenantID,
		arg.Title,
		arg.Slug,
		arg.CategoryID,
		arg.Status,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionMd,
		&i.Website,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListing = `-- name: GetListing :one
SELECT id, tenant_id, title, slug, summary, description_md, website, category_id, status, created_at, updated_at FROM listings
WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetListingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetListing(ctx context.Context, arg GetListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, getListing, arg.ID, arg.TenantID)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionMd,
		&i.Website,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listListings = `-- name: ListListings :many
SELECT id, tenant_id, title, slug, summary, description_md, website, category_id, status, created_at, updated_at FROM listings
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListListings(ctx context.Context, tenantID pgtype.UUID) ([]Listing, error) {
	rows, err := q.db.Query(ctx, listListings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.DescriptionMd,
			&i.Website,
			&i.CategoryID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListingStatus = `-- name: UpdateListingStatus :one
UPDATE listings
SET status = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, title, slug, summary, description_md, website, category_id, status, created_at, updated_at
`

type UpdateListingStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListingStatus, arg.ID, arg.TenantID, arg.Status)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionMd,
		&i.Website,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
