// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: marketplace.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks_market (
  author_tenant_id, name, version, price_cents, schema_json, bundle_url, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, author_tenant_id, name, version, price_cents, schema_json, bundle_url, status, created_at
`

type CreateBlockParams struct {
	AuthorTenantID pgtype.UUID `json:"author_tenant_id"`
	Name           string      `json:"name"`
	Version        string      `json:"version"`
	PriceCents     pgtype.Int4 `json:"price_cents"`
	SchemaJson     []byte      `json:"schema_json"`
	BundleUrl      pgtype.Text `json:"bundle_url"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (BlocksMarket, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.AuthorTenantID,
		arg.Name,
		arg.Version,
		arg.PriceCents,
		arg.SchemaJson,
		arg.BundleUrl,
		arg.Status,
	)
	var i BlocksMarket
	err := row.Scan(
		&i.ID,
		&i.AuthorTenantID,
		&i.Name,
		&i.Version,
		&i.PriceCents,
		&i.SchemaJson,
		&i.BundleUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes_market (
  author_tenant_id, name, thumb_url, price_cents, metadata_json, status
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, author_tenant_id, name, thumb_url, price_cents, metadata_json, status, created_at
`

type CreateThemeParams struct {
	AuthorTenantID pgtype.UUID `json:"author_tenant_id"`
	Name           string      `json:"name"`
	ThumbUrl       pgtype.Text `json:"thumb_url"`
	PriceCents     pgtype.Int4 `json:"price_cents"`
	MetadataJson   []byte      `json:"metadata_json"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (ThemesMarket, error) {
	row := q.db.QueryRow(ctx, createTheme,
		arg.AuthorTenantID,
		arg.Name,
		arg.ThumbUrl,
		arg.PriceCents,
		arg.MetadataJson,
		arg.Status,
	)
	var i ThemesMarket
	err := row.Scan(
		&i.ID,
		&i.AuthorTenantID,
		&i.Name,
		&i.ThumbUrl,
		&i.PriceCents,
		&i.MetadataJson,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const installItem = `-- name: InstallItem :one
INSERT INTO tenant_installs (
  tenant_id, item_type, item_id, version
) VALUES (
  $1, $2, $3, $4
) RETURNING id, tenant_id, item_type, item_id, version, status, created_at
`

type InstallItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ItemType string      `json:"item_type"`
	ItemID   pgtype.UUID `json:"item_id"`
	Version  pgtype.Text `json:"version"`
}

func (q *Queries) InstallItem(ctx context.Context, arg InstallItemParams) (TenantInstall, error) {
	row := q.db.QueryRow(ctx, installItem,
		arg.TenantID,
		arg.ItemType,
		arg.ItemID,
		arg.Version,
	)
	var i TenantInstall
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemType,
		&i.ItemID,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, author_tenant_id, name, version, price_cents, schema_json, bundle_url, status, created_at FROM blocks_market
WHERE status = 'published'
ORDER BY created_at DESC
`

func (q *Queries) ListBlocks(ctx context.Context) ([]BlocksMarket, error) {
	rows, err := q.db.Query(ctx, listBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlocksMarket
	for rows.Next() {
		var i BlocksMarket
		if err := rows.Scan(
			&i.ID,
			&i.AuthorTenantID,
			&i.Name,
			&i.Version,
			&i.PriceCents,
			&i.SchemaJson,
			&i.BundleUrl,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, author_tenant_id, name, thumb_url, price_cents, metadata_json, status, created_at FROM themes_market
WHERE status = 'published'
ORDER BY created_at DESC
`

func (q *Queries) ListThemes(ctx context.Context) ([]ThemesMarket, error) {
	rows, err := q.db.Query(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThemesMarket
	for rows.Next() {
		var i ThemesMarket
		if err := rows.Scan(
			&i.ID,
			&i.AuthorTenantID,
			&i.Name,
			&i.ThumbUrl,
			&i.PriceCents,
			&i.MetadataJson,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
