// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: marketplace_community.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommunityPost = `-- name: CreateCommunityPost :one
INSERT INTO community_posts (tenant_id, title, content, category)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, author_id, title, content, category, upvotes, created_at
`

type CreateCommunityPostParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Title    string      `json:"title"`
	Content  string      `json:"content"`
	Category string      `json:"category"`
}

func (q *Queries) CreateCommunityPost(ctx context.Context, arg CreateCommunityPostParams) (CommunityPost, error) {
	row := q.db.QueryRow(ctx, createCommunityPost,
		arg.TenantID,
		arg.Title,
		arg.Content,
		arg.Category,
	)
	var i CommunityPost
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Upvotes,
		&i.CreatedAt,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO community_reviews (tenant_id, listing_id, author_name, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, listing_id, author_name, rating, comment, created_at
`

type CreateReviewParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ListingID  pgtype.UUID `json:"listing_id"`
	AuthorName string      `json:"author_name"`
	Rating     int32       `json:"rating"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (CommunityReview, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.TenantID,
		arg.ListingID,
		arg.AuthorName,
		arg.Rating,
		arg.Comment,
	)
	var i CommunityReview
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ListingID,
		&i.AuthorName,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const installMarketplaceItem = `-- name: InstallMarketplaceItem :one
INSERT INTO marketplace_installs (tenant_id, type, external_id, config_json)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, type, external_id, config_json, installed_at
`

type InstallMarketplaceItemParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Type       string      `json:"type"`
	ExternalID string      `json:"external_id"`
	ConfigJson []byte      `json:"config_json"`
}

func (q *Queries) InstallMarketplaceItem(ctx context.Context, arg InstallMarketplaceItemParams) (MarketplaceInstall, error) {
	row := q.db.QueryRow(ctx, installMarketplaceItem,
		arg.TenantID,
		arg.Type,
		arg.ExternalID,
		arg.ConfigJson,
	)
	var i MarketplaceInstall
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.ExternalID,
		&i.ConfigJson,
		&i.InstalledAt,
	)
	return i, err
}

const listCommunityPosts = `-- name: ListCommunityPosts :many
SELECT id, tenant_id, author_id, title, content, category, upvotes, created_at FROM community_posts
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCommunityPosts(ctx context.Context, tenantID pgtype.UUID) ([]CommunityPost, error) {
	rows, err := q.db.Query(ctx, listCommunityPosts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityPost
	for rows.Next() {
		var i CommunityPost
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Upvotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstalledItems = `-- name: ListInstalledItems :many
SELECT id, tenant_id, type, external_id, config_json, installed_at FROM marketplace_installs
WHERE tenant_id = $1
ORDER BY installed_at DESC
`

func (q *Queries) ListInstalledItems(ctx context.Context, tenantID pgtype.UUID) ([]MarketplaceInstall, error) {
	rows, err := q.db.Query(ctx, listInstalledItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketplaceInstall
	for rows.Next() {
		var i MarketplaceInstall
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.ExternalID,
			&i.ConfigJson,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, tenant_id, listing_id, author_name, rating, comment, created_at FROM community_reviews
WHERE listing_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviews(ctx context.Context, listingID pgtype.UUID) ([]CommunityReview, error) {
	rows, err := q.db.Query(ctx, listReviews, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityReview
	for rows.Next() {
		var i CommunityReview
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ListingID,
			&i.AuthorName,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
