// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
  tenant_id, user_id, role
) VALUES (
  $1, $2, $3
) RETURNING tenant_id, user_id, role
`

type CreateMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TenantID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(&i.TenantID, &i.UserID, &i.Role)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT tenant_id, user_id, role FROM memberships
WHERE tenant_id = $1 AND user_id = $2 LIMIT 1
`

type GetMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TenantID, arg.UserID)
	var i Membership
	err := row.Scan(&i.TenantID, &i.UserID, &i.Role)
	return i, err
}
