// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTourState = `-- name: GetTourState :one
SELECT id, tenant_id, user_id, tour_id, status, last_step_index, updated_at FROM user_tour_states
WHERE tenant_id = $1 AND user_id = $2 AND tour_id = $3
`

type GetTourStateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	TourID   string      `json:"tour_id"`
}

func (q *Queries) GetTourState(ctx context.Context, arg GetTourStateParams) (UserTourState, error) {
	row := q.db.QueryRow(ctx, getTourState, arg.TenantID, arg.UserID, arg.TourID)
	var i UserTourState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TourID,
		&i.Status,
		&i.LastStepIndex,
		&i.UpdatedAt,
	)
	return i, err
}

const listTourStates = `-- name: ListTourStates :many
SELECT id, tenant_id, user_id, tour_id, status, last_step_index, updated_at FROM user_tour_states
WHERE tenant_id = $1 AND user_id = $2
`

type ListTourStatesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListTourStates(ctx context.Context, arg ListTourStatesParams) ([]UserTourState, error) {
	rows, err := q.db.Query(ctx, listTourStates, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTourState
	for rows.Next() {
		var i UserTourState
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.TourID,
			&i.Status,
			&i.LastStepIndex,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTourState = `-- name: UpsertTourState :one
INSERT INTO user_tour_states (tenant_id, user_id, tour_id, status, last_step_index, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (tenant_id, user_id, tour_id) DO UPDATE
SET status = $4, last_step_index = $5, updated_at = NOW()
RETURNING id, tenant_id, user_id, tour_id, status, last_step_index, updated_at
`

type UpsertTourStateParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	UserID        pgtype.UUID `json:"user_id"`
	TourID        string      `json:"tour_id"`
	Status        string      `json:"status"`
	LastStepIndex int32       `json:"last_step_index"`
}

func (q *Queries) UpsertTourState(ctx context.Context, arg UpsertTourStateParams) (UserTourState, error) {
	row := q.db.QueryRow(ctx, upsertTourState,
		arg.TenantID,
		arg.UserID,
		arg.TourID,
		arg.Status,
		arg.LastStepIndex,
	)
	var i UserTourState
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TourID,
		&i.Status,
		&i.LastStepIndex,
		&i.UpdatedAt,
	)
	return i, err
}
