// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personalisation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonalisationRule = `-- name: CreatePersonalisationRule :one
INSERT INTO personalisation_rules (
  tenant_id, rule_json, is_active
) VALUES (
  $1, $2, $3
) RETURNING id, tenant_id, rule_json, is_active, created_at
`

type CreatePersonalisationRuleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RuleJson []byte      `json:"rule_json"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreatePersonalisationRule(ctx context.Context, arg CreatePersonalisationRuleParams) (PersonalisationRule, error) {
	row := q.db.QueryRow(ctx, createPersonalisationRule, arg.TenantID, arg.RuleJson, arg.IsActive)
	var i PersonalisationRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuleJson,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRecommendations = `-- name: GetRecommendations :many
SELECT l.id, l.tenant_id, l.title, l.slug, l.summary, l.description_md, l.website, l.category_id, l.status, l.created_at, l.updated_at, r.score
FROM recommendations r
JOIN listings l ON r.listing_id = l.id
WHERE r.tenant_id = $1
ORDER BY r.score DESC
LIMIT $2
`

type GetRecommendationsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

type GetRecommendationsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Summary       pgtype.Text        `json:"summary"`
	DescriptionMd pgtype.Text        `json:"description_md"`
	Website       pgtype.Text        `json:"website"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Status        pgtype.Text        `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Score         float64            `json:"score"`
}

func (q *Queries) GetRecommendations(ctx context.Context, arg GetRecommendationsParams) ([]GetRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, getRecommendations, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecommendationsRow
	for rows.Next() {
		var i GetRecommendationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.DescriptionMd,
			&i.Website,
			&i.CategoryID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalisationRules = `-- name: ListPersonalisationRules :many
SELECT id, tenant_id, rule_json, is_active, created_at FROM personalisation_rules
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPersonalisationRules(ctx context.Context, tenantID pgtype.UUID) ([]PersonalisationRule, error) {
	rows, err := q.db.Query(ctx, listPersonalisationRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalisationRule
	for rows.Next() {
		var i PersonalisationRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuleJson,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
