// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
  tenant_id, code, name, price_cents, interval, features_json
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, code, name, price_cents, interval, features_json, is_active, created_at
`

type CreatePlanParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	PriceCents   int32       `json:"price_cents"`
	Interval     string      `json:"interval"`
	FeaturesJson []byte      `json:"features_json"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.PriceCents,
		arg.Interval,
		arg.FeaturesJson,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.PriceCents,
		&i.Interval,
		&i.FeaturesJson,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, tenant_id, code, name, price_cents, interval, features_json, is_active, created_at FROM plans
WHERE tenant_id = $1 AND is_active = true
ORDER BY price_cents
`

func (q *Queries) ListPlans(ctx context.Context, tenantID pgtype.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.PriceCents,
			&i.Interval,
			&i.FeaturesJson,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
