// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToFederationIndex(ctx context.Context, arg AddToFederationIndexParams) (FederationIndex, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAdCreative(ctx context.Context, arg CreateAdCreativeParams) (AdCreative, error)
	CreateAdZone(ctx context.Context, arg CreateAdZoneParams) (AdZone, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) (BlocksMarket, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCommunityPost(ctx context.Context, arg CreateCommunityPostParams) (CommunityPost, error)
	CreateEnterpriseAuditLog(ctx context.Context, arg CreateEnterpriseAuditLogParams) error
	CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOpsFinding(ctx context.Context, arg CreateOpsFindingParams) (OpsFinding, error)
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	CreatePersonalisationRule(ctx context.Context, arg CreatePersonalisationRuleParams) (PersonalisationRule, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (CommunityReview, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (ThemesMarket, error)
	CreateTrendSignal(ctx context.Context, arg CreateTrendSignalParams) (TrendSignal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error)
	GetDailyMetrics(ctx context.Context, arg GetDailyMetricsParams) ([]MetricsDaily, error)
	GetFederationOptIn(ctx context.Context, tenantID pgtype.UUID) (FederationOptin, error)
	GetFederationStats(ctx context.Context) (GetFederationStatsRow, error)
	GetListing(ctx context.Context, arg GetListingParams) (Listing, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetPost(ctx context.Context, arg GetPostParams) (Post, error)
	GetRecommendations(ctx context.Context, arg GetRecommendationsParams) ([]GetRecommendationsRow, error)
	GetSCIMDirectory(ctx context.Context, tenantID pgtype.UUID) (ScimDirectory, error)
	GetSSOProvider(ctx context.Context, tenantID pgtype.UUID) (SsoProvider, error)
	GetSubscriptionByStripeID(ctx context.Context, stripeSubID pgtype.Text) (Subscription, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTopListingsByEvents(ctx context.Context, arg GetTopListingsByEventsParams) ([]GetTopListingsByEventsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InstallItem(ctx context.Context, arg InstallItemParams) (TenantInstall, error)
	InstallMarketplaceItem(ctx context.Context, arg InstallMarketplaceItemParams) (MarketplaceInstall, error)
	ListAPIKeys(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error)
	ListActiveAdsForZone(ctx context.Context, zoneID pgtype.UUID) ([]AdCreative, error)
	ListAdZones(ctx context.Context, tenantID pgtype.UUID) ([]AdZone, error)
	ListBlocks(ctx context.Context) ([]BlocksMarket, error)
	ListCategories(ctx context.Context, tenantID pgtype.UUID) ([]Category, error)
	ListCommunityPosts(ctx context.Context, tenantID pgtype.UUID) ([]CommunityPost, error)
	ListEnterpriseAuditLogs(ctx context.Context, tenantID pgtype.UUID) ([]EnterpriseAuditLog, error)
	ListInstalledItems(ctx context.Context, tenantID pgtype.UUID) ([]MarketplaceInstall, error)
	ListListings(ctx context.Context, tenantID pgtype.UUID) ([]Listing, error)
	ListMedia(ctx context.Context, tenantID pgtype.UUID) ([]Medium, error)
	ListOpsFindings(ctx context.Context, tenantID pgtype.UUID) ([]OpsFinding, error)
	ListPages(ctx context.Context, tenantID pgtype.UUID) ([]Page, error)
	ListPersonalisationRules(ctx context.Context, tenantID pgtype.UUID) ([]PersonalisationRule, error)
	ListPlans(ctx context.Context, tenantID pgtype.UUID) ([]Plan, error)
	ListPosts(ctx context.Context, tenantID pgtype.UUID) ([]Post, error)
	ListReviews(ctx context.Context, listingID pgtype.UUID) ([]CommunityReview, error)
	ListThemes(ctx context.Context) ([]ThemesMarket, error)
	ListTopTrends(ctx context.Context, tenantID pgtype.UUID) ([]TrendSignal, error)
	ListWebhookEndpoints(ctx context.Context, tenantID pgtype.UUID) ([]WebhookEndpoint, error)
	LogFederationQuery(ctx context.Context, arg LogFederationQueryParams) error
	RecordListingEvent(ctx context.Context, arg RecordListingEventParams) (ListingEvent, error)
	ResolveOpsFinding(ctx context.Context, arg ResolveOpsFindingParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SearchFederationIndex(ctx context.Context, query string) ([]FederationIndex, error)
	UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) (Listing, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
	UpsertFederationOptIn(ctx context.Context, arg UpsertFederationOptInParams) (FederationOptin, error)
	UpsertSCIMDirectory(ctx context.Context, arg UpsertSCIMDirectoryParams) (ScimDirectory, error)
	UpsertSSOProvider(ctx context.Context, arg UpsertSSOProviderParams) (SsoProvider, error)
}

var _ Querier = (*Queries)(nil)
