// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopicCluster = `-- name: CreateTopicCluster :one
INSERT INTO seo_topic_clusters (
    tenant_id, slug, type, title, target_keywords, parent_hub_id, status, metadata_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, slug, type, title, target_keywords, parent_hub_id, status, metadata_json, created_at, updated_at
`

type CreateTopicClusterParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Slug           string      `json:"slug"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	TargetKeywords []string    `json:"target_keywords"`
	ParentHubID    pgtype.UUID `json:"parent_hub_id"`
	Status         string      `json:"status"`
	MetadataJson   []byte      `json:"metadata_json"`
}

func (q *Queries) CreateTopicCluster(ctx context.Context, arg CreateTopicClusterParams) (SeoTopicCluster, error) {
	row := q.db.QueryRow(ctx, createTopicCluster,
		arg.TenantID,
		arg.Slug,
		arg.Type,
		arg.Title,
		arg.TargetKeywords,
		arg.ParentHubID,
		arg.Status,
		arg.MetadataJson,
	)
	var i SeoTopicCluster
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.TargetKeywords,
		&i.ParentHubID,
		&i.Status,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSEOHealth = `-- name: GetLatestSEOHealth :one
SELECT id, tenant_id, score, details_json, captured_at FROM seo_health_snapshots 
WHERE tenant_id = $1 
ORDER BY captured_at DESC 
LIMIT 1
`

func (q *Queries) GetLatestSEOHealth(ctx context.Context, tenantID pgtype.UUID) (SeoHealthSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSEOHealth, tenantID)
	var i SeoHealthSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Score,
		&i.DetailsJson,
		&i.CapturedAt,
	)
	return i, err
}

const getSEOSettings = `-- name: GetSEOSettings :one
SELECT id, tenant_id, site_title_pattern, meta_description_pattern, default_og_image_url, canonical_base_url, robots_directives_json, noindex_sections_json, schema_profile, updated_at FROM tenant_seo_settings WHERE tenant_id = $1
`

func (q *Queries) GetSEOSettings(ctx context.Context, tenantID pgtype.UUID) (TenantSeoSetting, error) {
	row := q.db.QueryRow(ctx, getSEOSettings, tenantID)
	var i TenantSeoSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteTitlePattern,
		&i.MetaDescriptionPattern,
		&i.DefaultOgImageUrl,
		&i.CanonicalBaseUrl,
		&i.RobotsDirectivesJson,
		&i.NoindexSectionsJson,
		&i.SchemaProfile,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopicClusters = `-- name: ListTopicClusters :many
SELECT id, tenant_id, slug, type, title, target_keywords, parent_hub_id, status, metadata_json, created_at, updated_at FROM seo_topic_clusters WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTopicClusters(ctx context.Context, tenantID pgtype.UUID) ([]SeoTopicCluster, error) {
	rows, err := q.db.Query(ctx, listTopicClusters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoTopicCluster
	for rows.Next() {
		var i SeoTopicCluster
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.TargetKeywords,
			&i.ParentHubID,
			&i.Status,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSEOSettings = `-- name: UpsertSEOSettings :one
INSERT INTO tenant_seo_settings (
    tenant_id, site_title_pattern, meta_description_pattern, 
    default_og_image_url, canonical_base_url, robots_directives_json, 
    noindex_sections_json, schema_profile
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (tenant_id) DO UPDATE SET
    site_title_pattern = EXCLUDED.site_title_pattern,
    meta_description_pattern = EXCLUDED.meta_description_pattern,
    default_og_image_url = EXCLUDED.default_og_image_url,
    canonical_base_url = EXCLUDED.canonical_base_url,
    robots_directives_json = EXCLUDED.robots_directives_json,
    noindex_sections_json = EXCLUDED.noindex_sections_json,
    schema_profile = EXCLUDED.schema_profile,
    updated_at = NOW()
RETURNING id, tenant_id, site_title_pattern, meta_description_pattern, default_og_image_url, canonical_base_url, robots_directives_json, noindex_sections_json, schema_profile, updated_at
`

type UpsertSEOSettingsParams struct {
	TenantID               pgtype.UUID `json:"tenant_id"`
	SiteTitlePattern       pgtype.Text `json:"site_title_pattern"`
	MetaDescriptionPattern pgtype.Text `json:"meta_description_pattern"`
	DefaultOgImageUrl      pgtype.Text `json:"default_og_image_url"`
	CanonicalBaseUrl       pgtype.Text `json:"canonical_base_url"`
	RobotsDirectivesJson   []byte      `json:"robots_directives_json"`
	NoindexSectionsJson    []byte      `json:"noindex_sections_json"`
	SchemaProfile          pgtype.Text `json:"schema_profile"`
}

func (q *Queries) UpsertSEOSettings(ctx context.Context, arg UpsertSEOSettingsParams) (TenantSeoSetting, error) {
	row := q.db.QueryRow(ctx, upsertSEOSettings,
		arg.TenantID,
		arg.SiteTitlePattern,
		arg.MetaDescriptionPattern,
		arg.DefaultOgImageUrl,
		arg.CanonicalBaseUrl,
		arg.RobotsDirectivesJson,
		arg.NoindexSectionsJson,
		arg.SchemaProfile,
	)
	var i TenantSeoSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteTitlePattern,
		&i.MetaDescriptionPattern,
		&i.DefaultOgImageUrl,
		&i.CanonicalBaseUrl,
		&i.RobotsDirectivesJson,
		&i.NoindexSectionsJson,
		&i.SchemaProfile,
		&i.UpdatedAt,
	)
	return i, err
}
