// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  tenant_id, plan_id, status, stripe_sub_id, current_period_end
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, tenant_id, plan_id, status, current_period_end, stripe_sub_id, created_at
`

type CreateSubscriptionParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	PlanID           pgtype.UUID        `json:"plan_id"`
	Status           string             `json:"status"`
	StripeSubID      pgtype.Text        `json:"stripe_sub_id"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.PlanID,
		arg.Status,
		arg.StripeSubID,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.StripeSubID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, tenant_id, plan_id, status, current_period_end, stripe_sub_id, created_at FROM subscriptions
WHERE stripe_sub_id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.StripeSubID,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = $2, current_period_end = $3
WHERE stripe_sub_id = $1
RETURNING id, tenant_id, plan_id, status, current_period_end, stripe_sub_id, created_at
`

type UpdateSubscriptionStatusParams struct {
	StripeSubID      pgtype.Text        `json:"stripe_sub_id"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.StripeSubID, arg.Status, arg.CurrentPeriodEnd)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.StripeSubID,
		&i.CreatedAt,
	)
	return i, err
}
