// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
  name, slug, domains, theme_id, plan
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, slug, domains, theme_id, plan, created_at
`

type CreateTenantParams struct {
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	Domains []string    `json:"domains"`
	ThemeID pgtype.UUID `json:"theme_id"`
	Plan    pgtype.Text `json:"plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Domains,
		arg.ThemeID,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domains,
		&i.ThemeID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, domains, theme_id, plan, created_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domains,
		&i.ThemeID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, domains, theme_id, plan, created_at FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domains,
		&i.ThemeID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}
